language: node_js
node_js:
- lts/*
deploy:
  provider: heroku
  app: rocky-garden-16874
  api_key:
    secure: dRe1VG0+GHuaEVzNlq3ojFpNPd7D/8dzVuto2K3o/l+wfCHPR5X4d9Nd2MRWheaFQbuHLZZsMnvAJ3hgolnzhFWKSVPUblBmemj+Z4F52sqtMjrZV0JtteA5wnheFDZOJZ/QuE+y3FvomU9HgmI+UI8LehwiBIwUYnp7hK2qDlwHEfpOv6TcoIHjTBJcOywCP8lyRAfQLuT+mJNfsHf4lenzj1Q401AvGnRPyT5sfSy9Rrvpl3xH5dlgWSzsLM20ZkkzkGUAkgpck4f2YCSoaaKPpPuoL2sM8V4MrUk4RcM4H7CzZHwIZ7yuOdYsNpmTl55/bHgJLKc1JjEqoU3xU0n7vz9HqRZk6jLcLoz+wjp9QYBZyv8Mq+swFjF9y0W1Uu2oZWhKBs2Hx6mhuxGVHSPTe5CY38LOxp1GYVDRasNdgORmEJApQaTjkCxuiQdJ1aJzricd6w68g09y36or1W2BKlV9qHxw4FW5U56YPaCpKX5yKRkCoB6Cxg1F5RLe0VqkpeVHwgzRKTNTQcXbYlUQmKU5umMFh87Uk7GuMGi3p3UO0fGDT4ig9nSsPfLg109jyOWRNzeIlbqjlhiks7rbQN7S2q+sU2iBfIR08a6csK4jZ58GaHNqNvTe1UdaHPO+dY7gPDJrlohMQn06Xt8RPz7CMOoTanSuEFuCvlc=
